services:
  - docker

stages:
  - test

jobs:
  include:
    - stage: test
      language: minimal
      script:
        - docker volume create --name starter_data
        - docker-compose build
        - docker-compose run --entrypoint "python src/manage.py test src" api
        - docker-compose run --entrypoint "yarn test" client
