version: '3'

services:

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code

  db:
    image: postgres:alpine
    volumes:
      - notes-db:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code

volumes:
  notes-db:
    external: true
