version: '3'

services:

  db:
    image: postgres:12.0-alpine
    volumes:
      - starter_data:/var/lib/postgresql/data/

  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: 
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_DATABASE_NAME=${DJANGO_DATABASE_NAME}
      - DJANGO_DATABASE_USER=${DJANGO_DATABASE_USER}
      - DJANGO_DATABASE_HOST=${DJANGO_DATABASE_HOST}
      - DJANGO_DATABASE_PORT=${DJANGO_DATABASE_PORT}

  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - /code/node_modules
      - ./client:/code
    ports:
      - 3000:3000
    
  proxy:
    image: nginx:1.17.5-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 5000:80
    depends_on:
      - api
      - client

volumes:
  starter_data:
    external: true
