# Generated by Django 2.2.7 on 2019-11-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semestr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='parent_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='semestr.Semester'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='parent_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='semestr.Class'),
        ),
    ]
