apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: semestr-api
        image: danielgaldev/semestr-api
        ports:
          - containerPort: 8000
        env:
          - name: DJANGO_ALLOWED_HOSTS
            value: "['*']"
          - name: DJANGO_DEBUG
            value: "false"
          - name: DJANGO_DATABASE_NAME
            value: postgres
          - name: DJANGO_DATABASE_USER
            value: postgres
          - name: DJANGO_DATABASE_HOST
            value: db-cluster-ip
          - name: DJANGO_DATABASE_PORT
            value: "5432"
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secret-key
                key: DJANGO_SECRET_KEY
