apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
  labels:
    component: db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp"