# Generated by Django 2.2.7 on 2019-11-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='manager.ClassTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='parent_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='manager.Template'),
        ),
    ]
